### ISSUE TITLE
Support to MMLab models

### ISSUE THREAD

**Issue by xingyueye** [ModelTC/MQBench#102]
Hi~Have you test the support for models of MMLabs? I just used mqBench to quantize a simple cls_models and errors occurs like that: 
```
[MQBENCH] INFO: Quantize model Scheme: BackendType.Tensorrt Mode: Eval
[MQBENCH] INFO: Weight Qconfig:
    FakeQuantize: LearnableFakeQuantize Params: {}
    Oberver:      MinMaxObserver Params: Symmetric: True / Bitwidth: 8 / Per channel: True / Pot scale: False / Extra kwargs: {}
[MQBENCH] INFO: Activation Qconfig:
    FakeQuantize: LearnableFakeQuantize Params: {}
    Oberver:      EMAMinMaxObserver Params: Symmetric: True / Bitwidth: 8 / Per channel: False / Pot scale: False / Extra kwargs: {}
Traceback (most recent call last):
  File "my_python_path/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "my_python_path/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 94, in new_func
    if not isinstance(args[0], torch.nn.Module):
TypeError: 'ImageClassifier' object is not subscriptable
python-BaseException
```
Are there some unfittness between MMLab and MQbench, or problems of my envs version? Hope for your help

**Comment by Tracin** [comment]
We find it is slightly difficult to support MMLab, you have to modify the model very carefully.

**Comment by xingyueye** [comment]
> We find it is slightly difficult to support MMLab, you have to modify the model very carefully.

Do you have any experience to share?
