### ISSUE TITLE
Advanced_ptq for YOLOv5: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by xingyueye** [ModelTC/MQBench#107]
Hi, I try to apply mqbench for newest verison yolov5 project, But this problem occurs when `ptq_reconstruction`
```
[MQBENCH] INFO: learn the scale for model_model_0_conv_act_post_act_fake_quantizer
[MQBENCH] INFO: learn the scale for model_model_1_act_post_act_fake_quantizer
Init alpha to be FP32
Init alpha to be FP32
[MQBENCH] INFO: The world size is 1.
[MQBENCH] INFO: start tuning by adaround
Traceback (most recent call last):
  File "/***yolov5/mqbench_ptq.py", line 480, in <module>
    main(opt)
  File "/***/yolov5/mqbench_ptq.py", line 453, in main
    run(**vars(opt))
  File "/***/envs/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/***/yolov5/mqbench_ptq.py", line 273, in run
    model = ptq_reconstruction(model, stacked_tensor, ptq_reconstruction_config)
  File "/***/envs/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/advanced_ptq.py", line 668, in ptq_reconstruction
  File "/***/envs/lib/python3.8/site-packages/MQBench-0.0.6-py3.8.egg/mqbench/advanced_ptq.py", line 347, in subgraph_reconstruction
  File "/***envs/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/***/envs/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
Hope for your reply. Or the example of yolov5 is also appreciated.

**Comment by xingyueye** [comment]
BTW, this error occurs at the first block, as below:
```
[MQBENCH] INFO: 
def forward(self, model_model_0_space2depth_post_act_fake_quantizer):
    model_model_0_conv_conv = getattr(self.model.model, "0").conv.conv(model_model_0_space2depth_post_act_fake_quantizer);  model_model_0_space2depth_post_act_fake_quantizer = None
    model_model_0_conv_act = getattr(self.model.model, "0").conv.act(model_model_0_conv_conv);  model_model_0_conv_conv = None
    model_model_0_conv_act_post_act_fake_quantizer = self.model_model_0_conv_act_post_act_fake_quantizer(model_model_0_conv_act);  model_model_0_conv_act = None
    model_model_1_conv = getattr(self.model.model, "1").conv(model_model_0_conv_act_post_act_fake_quantizer);  model_model_0_conv_act_post_act_fake_quantizer = None
    model_model_1_act = getattr(self.model.model, "1").act(model_model_1_conv);  model_model_1_conv = None
    model_model_1_act_post_act_fake_quantizer = self.model_model_1_act_post_act_fake_quantizer(model_model_1_act);  model_model_1_act = None
    return model_model_1_act_post_act_fake_quantizer
```
I guess that if the `space2depth` module causes this problem. I have replaced the original “Focus” module  with "space2depth" module as your doc recommended

**Comment by PannenetsF** [comment]
Thanks for the feedback! 
You can provide your yolov5 model's defination file so I can deal with this. 
BTW, I guess this might be resolved by adding `space2depth` module into `customed_leaf_module`.
https://github.com/ModelTC/MQBench/blob/main/mqbench/prepare_by_platform.py#L375-L376

**Comment by xingyueye** [comment]
Thanks, adding `space2depth/Focus` into `customed_leaf_module` does not work.
My complementation is based on the newest version of yolov5: https://github.com/ultralytics/yolov5
And the only changes of model's defination are postprocess spliting and space2depth inserting, as your recommentation.
The main adv-ptq process likes below:
```
    config = './qat_w8a8_trt.yaml'
    if config:
        config = parse_config(config)
        ptq_reconstruction_config = config.quantize.reconstruction

    leaf_module = (FrozenBatchNorm2d, Focus)
    prepare_custom_config_dict = {'extra_qconfig_dict': config.extra_prepare_dict.extra_qconfig_dict,
                                  'leaf_module': leaf_module}
    backend = BackendType.Tensorrt
    model = prepare_by_platform(model, backend, prepare_custom_config_dict) 
    model = model.to(device)
    enable_calibration_woquantization(model, quantizer_type='act_fake_quant')
    idx = 0
    stacked_tensor = []

    for batch_i, (im, targets,_,_) in enumerate(caliib_loader):
        img = im.to(device, non_blocking=True)
        img = img.float()
        img /= 255.0
        stacked_tensor.append(img)
        _ = model(img)

    enable_calibration_woquantization(model, quantizer_type='weight_fake_quant')
    model(torch.randn((1, 3, 640, 640)).cuda())
    # ptq_reconstruction loop
    model = ptq_reconstruction(model, stacked_tensor, ptq_reconstruction_config)        
    # start ptq_reconstruction
    enable_quantization(model) 
```
Naive-PTQ process is correct, But Adv-PTQ occurs error.

**Comment by xingyueye** [comment]
My problems has been sovled. A small property `@torch.no_grad()` is before my function. It tooks a lot of work to find it ====

**Comment by nmgbj** [comment]
hi,
i do advance_ptq as yours, but error occured 'RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().'  have you ever had this error? or do you know how to resolve it ?

**Comment by PannenetsF** [comment]
> 

Hi, you'd better open a new issue, with some code to reproduce it attached.
