### ISSUE TITLE
How to save checkpoints during QAT?

### ISSUE THREAD

**Issue by xingyueye** [ModelTC/MQBench#114]
Hi~I want to compress yolov5 with MQbench. This problem occurs during the QAT process: 
```
Traceback (most recent call last):
  File "xxx/tools/mqbench_qat.py", line 144, in <module>
    main(args)
  File "xxx/tools/mqbench_qat.py", line 133, in main
    trainer.eval_and_save()
  File "xxx/core/engine_qat.py", line 146, in eval_and_save
    save_checkpoint(ckpt, (is_val_epoch) and (self.ap == self.best_ap), save_ckpt_dir, model_name='last_ckpt')
  File "xxx/utils/checkpoint.py", line 43, in save_checkpoint
    torch.save(ckpt, filename)
  File "xxx/env/lib/python3.7/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "xxx/env/lib/python3.7/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'ObserverBase.__init__.<locals>.PerChannelLoadHook'
```
I guess the reason is that the Quantized model can not be saved correctly with normal `torch.save()` function. Pls help me with how to save the checkpoints during QAT.

**Comment by Tracin** [comment]
What is in the `ckpt` variable?
https://github.com/ModelTC/MQBench/blob/main/test/load_ckpt/test_load_ckpt.py

**Comment by aksenventwo** [comment]
I guess it is this `self.load_state_dict_hook = PerChannelLoadHook(self)`, I also encountered it, changed it to `torch.save(model_1.state_dict(), 'saved_model.ckpt')` is ok，don't use `torch.save(model)` directly. or call directly `PerChannelLoadHook(self)` without assignment.
