### ISSUE TITLE
显存占用高

### ISSUE THREAD

**Issue by PuNeal** [ModelTC/MQBench#144]
我在使用adaround微调mobilenet-v2模型参数时，发现显存占用不断增加，最后爆掉了。
```python
Traceback (most recent call last):                                                                                                                            
  File "application\imagenet_example\PTQ\ptq\ptq.py", line 84, in <module>                                                                                    
    model, cali_data, config.quantize.reconstruction)                                                                                                         
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\mqbench-0.0.6-py3.7.egg\mqbench\advanced_ptq.py", line 654, in ptq_reconstruction               
    store_inp=False, store_oup=True, keep_gpu=config.keep_gpu)                                                                                                
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\mqbench-0.0.6-py3.7.egg\mqbench\advanced_ptq.py", line 118, in save_inp_oup_data                
    _ = model(to_device(batch, device))                                                                                                                       
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\fx\graph_module.py", line 308, in wrapped_call                                            
    return cls_call(self, *args, **kwargs)                                                                                                                    
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\fx\graph_module.py", line 308, in wrapped_call                                            
    return cls_call(self, *args, **kwargs)                                                                                                                    
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl                                            
    result = self.forward(*input, **kwargs)                                                                                                                   
  File "<eval_with_key_3>", line 16, in forward                                                                                                               
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl                                            
    result = self.forward(*input, **kwargs)                                                                                                                   
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\nn\modules\batchnorm.py", line 140, in forward                                            
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)                                                                                
  File "E:\software\miniconda3\envs\mqbench\lib\site-packages\torch\nn\functional.py", line 2150, in batch_norm                                               
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled                                                     
RuntimeError: CUDA out of memory. Tried to allocate 294.00 MiB (GPU 0; 12.00 GiB total capacity; 9.73 GiB already allocated; 0 bytes free; 10.00 GiB reserved 
in total by PyTorch)                                                                                                                                          
```
请问是什么原因导致的？有什么解决办法吗？

**Comment by PannenetsF** [comment]
可以把keep gpu开成false
