### ISSUE TITLE
使用MQBench给CenterPoint做量化感知训练时出现问题

### ISSUE THREAD

**Issue by majaya** [ModelTC/MQBench#169]
您好：
在使用MQBench给CenterPoint模型做量化感知训练时，模型QAT训练可以进行，但是导出模型时报错。
具体情况如下（先介绍一下工程修改情况，方便您判断问题）：
1. 模型结构：
对CenterPoint模型做了结构上的调整，将VFE和稀疏卷积那块代码整合到一起（这部分不做量化）
将RPN和Head整合到一起，这部分就是我做QAT的网络结构，将原来工程中Head部分的后处理独立出来，使得RPN和Head组成干净的网络，RPN和Head组成的网络结构如下：

![image](https://user-images.githubusercontent.com/37564415/184086177-792748d7-3370-4a9e-8634-f53404d1cb9c.png)

```
model_pre = build_detector(cfg.model_pre, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
model_inf = build_detector(cfg.model_infer, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
model_pos = build_detector(cfg.model_post, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
```
中间那个model_inf就是上面说的要做量化的纯净网络,包含原CenterPoint中的RPN和MultiGroupHead结构

2. 网络量化
模型量化这块没有太多的参数配置，只是设置了observer和fakequantize

```
    if quant:
        # 插入伪量化节点
        logger.info("prepare quantize model_inf")
        prepare_custom_config_dict = {}
        extra_qconfig_dict = cfg.quant.prepare_args.extra_qconfig_dict
        prepare_custom_config_dict['extra_qconfig_dict'] = extra_qconfig_dict
        model_inf = prepare_by_platform(model_inf, BackendType.Tensorrt, prepare_custom_config_dict)
        model_inf.cuda()
        trainer.model_inf = model_inf
        print(model_inf)
```

插入量化节点之后网路模型变为（局部）：
![image](https://user-images.githubusercontent.com/37564415/184087812-0dbd105b-99c9-4e78-9850-9a7efbfa7feb.png)
插入量化节点之前的参考如下（局部）：
![image](https://user-images.githubusercontent.com/37564415/184087967-b3aeefae-1a58-4942-94be-c867f465e2c9.png)
模型可以正常运行QAT训练
但是调用convert_deploy时，报错，报错内容如下：
=============================================================================================
```
[MQBENCH] INFO: Merge BN for deploy.
[MQBENCH] INFO: Export to onnx.
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:19: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/observer.py:263: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:23: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:29: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:37: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:24: TracerWarning: resize_ can't be represented in the JIT at the moment, so we won't connect any uses of this value with its current trace. If you happen to use it again, it will show up as a constant in the graph.
/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/fake_quantize/fixed.py:25: TracerWarning: resize_ can't be represented in the JIT at the moment, so we won't connect any uses of this value with its current trace. If you happen to use it again, it will show up as a constant in the graph.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation on block inputs. This changes graph semantics.
Traceback (most recent call last):
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/convert_deploy.py", line 69, in convert_onnx
ImportError: cannot import name 'ONNXCheckerError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljt/CenterPoint/tools/export_rpn_qat_.py", line 147, in <module>
    main()
  File "/home/ljt/CenterPoint/tools/export_rpn_qat_.py", line 138, in main
    convert_deploy(model, deploy_backend, dummy_input=fake_input, output_path=RPN_ONNX_PATH)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/convert_deploy.py", line 182, in convert_deploy
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/convert_deploy.py", line 87, in convert_onnx
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 468, in _model_to_graph
    module=module)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/torch/onnx/utils.py", line 137, in _optimize_graph
    torch._C._jit_pass_onnx_remove_inplace_ops_for_onnx(graph, module)
RuntimeError: kind_.is_prim() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":1098, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::copy doesn't have one either. We don't know if this op has side effects.

Process finished with exit code 1
```
=============================================================================================
export model的脚本如下：

    # build model
    model = build_detector(cfg.model_infer, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
    if EXPORT_QUANT:
        # quant model
        logger.info("prepare quantize model_inf")
        prepare_custom_config_dict = {}
        extra_qconfig_dict = cfg.quant.prepare_args.extra_qconfig_dict
        prepare_custom_config_dict['extra_qconfig_dict'] = extra_qconfig_dict
        model = prepare_by_platform(model, BackendType.Tensorrt, prepare_custom_config_dict)
    # model.cuda()
    print(model)
    # load ckpt
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")

    # put model on gpus
    if distributed:
        model = apex.parallel.convert_syncbn_model(model)
        model = DistributedDataParallel(
            model.cuda(cfg.local_rank),
            device_ids=[cfg.local_rank],
            output_device=cfg.local_rank,
            # broadcast_buffers=False,
            find_unused_parameters=True,
        )
    else:
        model = model.cuda()

    model.eval()

    if EXPORT_QUANT:
        # deploy model
        logger.info("deploy quant model")
        deploy_backend = BackendType.Tensorrt
        fake_input = torch.randn(PPRPN_SHAPE).cuda()
        convert_deploy(model, deploy_backend, dummy_input=fake_input, output_path=RPN_ONNX_PATH)

请帮忙查看一下问题，是否是版本等问题，谢谢。

**Comment by Tracin** [comment]
尝试模型在`prepare_by_platform`前做`torch.onnx.export` 或`convert_deploy`查看是否报错

**Comment by majaya** [comment]
> 尝试模型在`prepare_by_platform`前做`torch.onnx.export` 或`convert_deploy`查看是否报错

尝试在`prepare_by_platform`之前做，用`torch.onnx.export` 没问题可以导出模型，用`convert_deploy`报错。

Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/home/ljt/pycharm-community-2021.1.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ljt/pycharm-community-2021.1.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ljt/CenterPoint/tools/export_rpn_qat_.py", line 171, in <module>
    main()
  File "/home/ljt/CenterPoint/tools/export_rpn_qat_.py", line 126, in main
    convert_deploy(model, deploy_backend, dummy_input=fake_input, output_path=RPN_ONNX_PATH)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/convert_deploy.py", line 180, in convert_deploy
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/site-packages/MQBench-0.0.6-py3.6.egg/mqbench/utils/utils.py", line 73, in deepcopy_graphmodule
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ljt/anaconda3/envs/cp_env_pytorch1.8/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
