### ISSUE TITLE
使用的transformers版本是多少？

### ISSUE THREAD

**Issue by HawkL327** [ModelTC/MQBench#173]
Traceback (most recent call last):
  File "image_classification.py", line 28, in <module>
    from transformers.utils.fx import HFTracer, get_concrete_args
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/fx.py", line 30, in <module>
    from torch.fx.proxy import ParameterProxy
ImportError: cannot import name 'ParameterProxy' from 'torch.fx.proxy' (/opt/conda/lib/python3.8/site-packages/torch/fx/proxy.py)

**Comment by PannenetsF** [comment]
看起来是torch版本的问题，试下torch1.10
