### ISSUE TITLE
Try to convert my model but get error

### ISSUE THREAD

**Issue by szu-lisili** [ModelTC/MQBench#212]
Hi, this is a nice work! but when I try to deploy my model follow the guidence from:
[Deploy Just in 4 Lines](https://mqbench.readthedocs.io/en/latest/get_started/quick_start_deploy.html)
```
 model = denseFCN2.normal_denseFCN(bn_in='bn')  # 
    model.eval()
    backend = BackendType.OPENVINO
    model = prepare_by_platform(model, backend)
    enable_calibration(model)
    enable_quantization(model)
    input_shape = {'data': [10, 3, 224, 224]}
    convert_deploy(model, backend, input_shape)
```
I got the error:
```
E:\pyfile\quantization_for_tamper\mqbench\fake_quantize\lsq.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.observer_enabled[0] == 1:
E:\pyfile\quantization_for_tamper\mqbench\fake_quantize\lsq.py:55: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self.scale.data.clamp_(min=self.eps.item())
E:\pyfile\quantization_for_tamper\mqbench\fake_quantize\lsq.py:57: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.fake_quant_enabled[0] == 1:
Traceback (most recent call last):
  File "E:/pyfile/quantization_for_tamper/mqbench_torch_to_onnx.py", line 67, in <module>
    export_onnx(prepared_model, dummy_input, 'mqbench_denseFCN_insert_fakequant.onnx')
  File "E:\pyfile\quantization_for_tamper\utils.py", line 74, in export_onnx
    dynamic_axes={'x': {0: 'batch'}}
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\__init__.py", line 309, in export
    export_modules_as_functions)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\utils.py", line 122, in export
    custom_opsets=custom_opsets, export_modules_as_functions=export_modules_as_functions)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\utils.py", line 724, in _export
    dynamic_axes=dynamic_axes)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\onnx\utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\jit\_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\jit\_trace.py", line 132, in forward
    self._force_outplace,
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\anaconda3\envs\py37\lib\site-packages\torch\fx\graph_module.py", line 630, in wrapped_call
    raise e.with_traceback(None)
RuntimeError: shape '[8, 1, 1, 1]' is invalid for input of size 1

Process finished with exit code 1
```
I use pytorch to define my model, you can see from:
[](https://github.com/szu-lisili/first_rep/blob/master/denseFCN2.py)
the model is not complex. is there any one help me?/(ㄒoㄒ)/~~

**Comment by szu-lisili** [comment]
> 

model file: https://github.com/szu-lisili/first_rep/blob/master/denseFCN2.py

**Comment by Haleski47** [comment]
i also meet the similar problem and wonder why...
