### ISSUE TITLE
reassign[name] = swap_module(mod, mapping, {})

### ISSUE THREAD

**Issue by Wenqian1228** [ModelTC/MQBench#57]
Hi,

I was trying to do PTQ on my own PyTorch while the following error occurred:
`ypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)`
 
The full error is:

```
Traceback (most recent call last):
  File "ptq_test.py", line 162, in <module>
    model = prepare_by_platform(net, BackendType.Tensorrt, extra_config)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/prepare_by_platform.py", line 336, in prepare_by_platform
    prepared = quantizer.prepare(graph_module, qconfig)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/custom_quantizer.py", line 70, in prepare
    model = self._weight_quant(model, qconfig)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/custom_quantizer.py", line 131, in _weight_quant
    self._qat_swap_modules(model, self.additional_qat_module_mapping)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/custom_quantizer.py", line 251, in _qat_swap_modules
    root = self._convert(root, all_mappings, inplace=True)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/custom_quantizer.py", line 278, in _convert
    self._convert(mod, mapping, True, new_scope)
  File "/home/wenqianzhao/tmp2022/Simple-SR/mqbench/custom_quantizer.py", line 279, in _convert
    reassign[name] = swap_module(mod, mapping, {})
  File "/home/wenqianzhao/anaconda3/envs/mqbench/lib/python3.8/site-packages/torch/quantization/quantize.py", line 534, in swap_module
    new_mod = mapping[type(mod)].from_float(mod)
  File "/home/wenqianzhao/anaconda3/envs/mqbench/lib/python3.8/site-packages/torch/nn/intrinsic/qat/modules/conv_fused.py", line 423, in from_float
    return super(ConvReLU2d, cls).from_float(mod)
  File "/home/wenqianzhao/anaconda3/envs/mqbench/lib/python3.8/site-packages/torch/nn/qat/modules/conv.py", line 52, in from_float
    qat_conv.weight = mod.weight
  File "/home/wenqianzhao/anaconda3/envs/mqbench/lib/python3.8/site-packages/torch/nn/modules/module.py", line 968, in __setattr__
    raise TypeError("cannot assign '{}' as parameter '{}' "
TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
```

<img width="1061" alt="Screen Shot 2022-03-16 at 11 46 19 PM" src="https://user-images.githubusercontent.com/36410912/158639868-a628859b-8b5d-4c93-a3e5-271b6ede2917.png">

Attached is code to reproduce the error:
```
import math
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter

from mqbench.prepare_by_platform import prepare_by_platform   # add quant nodes for specific Backend
from mqbench.prepare_by_platform import BackendType           # contain various Backend, contains Academic.
from mqbench.utils.state import enable_calibration            # turn on calibration algorithm, determine scale, zero_point, etc.
from mqbench.utils.state import enable_quantization  

from mqbench.fake_quantize import FixedFakeQuantize
from mqbench.observer import MSEObserver


extra_config = {
    'w_observer': MSEObserver,                                # custom weight observer
    'a_observer': MSEObserver,                                # custom activation observer
    'w_fakequantize': FixedFakeQuantize,                      # custom weight fake quantize function
    'a_fakequantize': FixedFakeQuantize,                      # custom activation fake quantize function
    'w_qscheme': {
        'bit': 8,                                             # custom bitwidth for weight,
        'symmetry': False,                                    # custom whether quant is symmetric for weight,
        'per_channel': True,                                  # custom whether quant is per-channel or per-tensor for weight,
        'pot_scale': False,                                   # custom whether scale is power of two for weight.
    },
    'a_qscheme': {
        'bit': 8,                                             # custom bitwidth for activation,
        'symmetry': False,                                    # custom whether quant is symmetric for activation,
        'per_channel': True,                                  # custom whether quant is per-channel or per-tensor for activation,
        'pot_scale': False,                                   # custom whether scale is power of two for activation.
    }
}




class Scale(nn.Module):
    def __init__(self, init_value=1e-3):
        super(Scale, self).__init__()
        self.scale = Parameter(torch.FloatTensor([init_value]))

    def forward(self, x):
        return x * self.scale


class AWRU(nn.Module):
    def __init__(self, nf, kernel_size, wn, act=nn.ReLU(True)):
        super(AWRU, self).__init__()
        self.res_scale = Scale(1)
        self.x_scale = Scale(1)

        self.body = nn.Sequential(
            wn(nn.Conv2d(nf, nf, kernel_size, padding=kernel_size//2)),
            act,
            wn(nn.Conv2d(nf, nf, kernel_size, padding=kernel_size//2)),
        )

    def forward(self, x):
        res = self.res_scale(self.body(x)) + self.x_scale(x)
        return res


class AWMS(nn.Module):
    def __init__(self, nf, out_chl, wn, act=nn.ReLU(True)):
        super(AWMS, self).__init__()
        self.tail_k3 = wn(nn.Conv2d(nf, nf, 3, padding=3//2, dilation=1))
        self.tail_k5 = wn(nn.Conv2d(nf, nf, 5, padding=5//2, dilation=1))
        self.scale_k3 = Scale(0.5)
        self.scale_k5 = Scale(0.5)
        self.fuse = wn(nn.Conv2d(nf, nf, 3, padding=3 // 2))
        self.act = act
        self.w_conv = wn(nn.Conv2d(nf, out_chl, 3, padding=3//2))

    def forward(self, x):
        x0 = self.scale_k3(self.tail_k3(x))
        x1 = self.scale_k5(self.tail_k5(x))
        cur_x = x0 + x1

        fuse_x = self.act(self.fuse(cur_x))
        out = self.w_conv(fuse_x)

        return out


class LFB(nn.Module):
    def __init__(self, nf, wn, act=nn.ReLU(inplace=True)):
        super(LFB, self).__init__()
        self.b0 = AWRU(nf, 3, wn=wn, act=act)
        self.b1 = AWRU(nf, 3, wn=wn, act=act)
        self.b2 = AWRU(nf, 3, wn=wn, act=act)
        self.b3 = AWRU(nf, 3, wn=wn, act=act)
        self.reduction = wn(nn.Conv2d(nf * 4, nf, 3, padding=3//2))
        self.res_scale = Scale(1)
        self.x_scale = Scale(1)

    def forward(self, x):
        x0 = self.b0(x)
        x1 = self.b1(x0)
        x2 = self.b2(x1)
        x3 = self.b3(x2)
        res = self.reduction(torch.cat([x0, x1, x2, x3], dim=1))

        return self.res_scale(res) + self.x_scale(x)


class WeightNet(nn.Module):
    def __init__(self, config):
        super(WeightNet, self).__init__()

        in_chl = config.IN_CHANNEL
        nf = config.N_CHANNEL
        n_block = config.RES_BLOCK
        out_chl = config.N_WEIGHT
        scale = config.SCALE

        act = nn.ReLU(inplace=True)
        wn = lambda x: nn.utils.weight_norm(x)

        rgb_mean = torch.FloatTensor([0.4488, 0.4371, 0.4040]).view([1, 3, 1, 1]) 
        self.register_buffer('rgb_mean', rgb_mean)

        self.head = nn.Sequential(
            wn(nn.Conv2d(in_chl, nf, 3, padding=3//2)),
            act,
        )

        body = []
        for i in range(n_block):
            body.append(LFB(nf, wn=wn, act=act))
        self.body = nn.Sequential(*body)

        self.up = nn.Sequential(
            wn(nn.Conv2d(nf, nf * scale ** 2, 3, padding=3//2)),
            act,
            nn.PixelShuffle(upscale_factor=scale)
        )

        self.tail = AWMS(nf, out_chl, wn, act=act)

    def forward(self, x):
        x = x - self.rgb_mean
        x = self.head(x)
        x = self.body(x)
        x = self.up(x)
        out = self.tail(x)

        return out


if __name__ == '__main__':
    from easydict import EasyDict as edict

    config = edict()
    config.IN_CHANNEL = 3
    config.N_CHANNEL = 32
    config.RES_BLOCK = 4
    config.N_WEIGHT = 72
    config.SCALE = 2

    net = WeightNet(config).cuda()
    net.eval()
    model = prepare_by_platform(net, BackendType.Tensorrt, extra_config)

    cnt = 0
    for p in net.parameters():
        cnt += p.numel()
    print(cnt)

    x = torch.randn(1, 3, 32, 32).cuda()
    out = net(x)
    print(out.size())

```

**Comment by Tracin** [comment]
I figure out this is because of `weight_norm` split the weight into `weight_g` and `weight_v` meanwhile make `weight` an `Tensor`,
it is not possable to quantize weight at this moment. 
You have to well define how to quantize weight under this situation, either `Q(weight_g)` X `Q(weight_v)` or `Q(weight_g X weight_v)`, you can achieve this by define another swapped module.
